# Generated by Django 4.2.20 on 2025-05-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_aadhar_card_no_user_pan_card_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card_front', models.FileField(blank=True, null=True, upload_to='user_doc')),
                ('aadhar_card_back', models.FileField(blank=True, null=True, upload_to='user_doc')),
                ('pan_card_front', models.FileField(blank=True, null=True, upload_to='user_doc')),
                ('driving_licence', models.FileField(blank=True, null=True, upload_to='user_doc')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_document_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_document'),
        ),
    ]
