# Generated by Django 4.2.20 on 2025-05-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_document_user_user_document_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_document_data',
        ),
        migrations.AlterField(
            model_name='user_document',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='myapp.user'),
        ),
    ]
