# Generated by Django 4.2 on 2025-05-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_user_document_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_document',
            name='user_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='myapp.user'),
        ),
    ]
