# Generated by Django 4.2 on 2025-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ad_admin_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
