# Generated by Django 4.2 on 2025-05-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ad_sub_title_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_document',
            name='user_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_document', to='myapp.user'),
        ),
    ]
