# Generated by Django 5.0.6 on 2025-05-06 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_name_blog_title_blog_blog_category_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
