# Generated by Django 5.0.6 on 2025-05-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_token_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='price',
            field=models.IntegerField(),
        ),
    ]
