# Generated by Django 5.0.6 on 2025-05-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_certifications_grower_utility_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='berry_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('nft_code', models.CharField(blank=True, max_length=100, null=True)),
                ('nft_label', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
