# Generated by Django 5.0.6 on 2025-05-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_berry_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='berry_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('harvest_date', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_grams', models.IntegerField(blank=True, null=True)),
                ('carbon_offset_kg', models.FloatField(blank=True, null=True)),
                ('traceability_qr', models.CharField(blank=True, max_length=100, null=True)),
                ('current_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('berry_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.berry_types')),
                ('certifications', models.ManyToManyField(blank=True, to='myapp.certifications')),
                ('farm_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.grower')),
                ('utility_tags', models.ManyToManyField(blank=True, to='myapp.utility_tags')),
            ],
        ),
    ]
