# Generated by Django 5.0.6 on 2025-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_berry_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berry_batch',
            name='harvest_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
